package link.botwmcs.ltsxlogica.api.mastery;

public enum MasteryResult {
    SUCCESS, UNKNOWN_DEFINITION, NOT_UNLOCKED, SLOT_LOCKED, SLOT_NOT_ACTIVATED, SLOT_OCCUPIED,
    LEVEL_TOO_LOW, SERIES_MISMATCH, CONFLICT, INVALID_ITEM, INVENTORY_FULL, STALE_REVISION, INVALID_REQUEST
}
